services:
  nats:
    container_name: nats-server
    image: nats
    ports:
      - "4222:4222"

  rabbit-mq:
    container_name: rabbitMq
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672' # server
      - '15672:15672' # gui
    env_file:
      - .env

  # 1.API Gateway service
  api_gateway_service:
    container_name: api-gateway-service
    build: ./api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000

  # 2. Billing Service
  billing_service:
    container_name: billing-service
    build:
      context: ./billing
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./billing/src:/usr/src/app/src
    command: npm run start:dev

  # 3. Notification Service
  notification_service:
    container_name: notification-service
    build:
      context: ./notification
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./notification/src:/usr/src/app/src
    command: npm run start:dev

  # 4. Payment Service
  payment-service-db:
    container_name: payment-service-db
    image: postgres
    env_file:
      - ./payment/.env
    ports:
      - '5430:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data  #how to make data persist after docker restarts

  payment-service-db-gui:
    container_name: payment-service-db-gui
    image: dpage/pgadmin4
    depends_on:
      - payment-service-db
    env_file:
      - ./payment/.env
    ports:
      - '15432:80'

  payment-service:
    container_name: payment-service
    build:
      context: ./payment
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    volumes:
      - ./payment/src:/usr/src/app/src
    command: npm run start:dev

  # 5. Subscription Service
  subscription_service:
    container_name: subscription-service
    build:
      context: ./subscription
      dockerfile: Dockerfile
    ports:
      - "3004:3000"
    volumes:
      - ./subscription/src:/usr/src/app/src
    command: npm run start:dev

  # 6.User Service
  user_service_db:
    container_name: user-service-db
    image: mysql
    ports:
      - '3307:3307'
    env_file:
      - ./user/.env

  user_service_db_admin_panel:
    container_name: user_service_db_admin_panel
    image: phpmyadmin
    restart: always
    env_file:
      - ./user/.env
    ports:
      - "8080:80"

  user_service:
    container_name: user-service
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - user_service_db
    volumes:
      - ./user/src:/usr/src/app/src






