services:
  nats:
    container_name: nats-server
    image: nats
    ports:
      - "4222:4222"

  # 1.API Gateway service
  api_gateway_service:
    container_name: api-gateway-service
    build: ./api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000

  # 2. Billing Service
  billing_service:
    container_name: billing-service
    build:
      context: ./billing
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./billing/src:/usr/src/app/src
    command: npm run start:dev

  # 3. Notification Service
  notification_service:
    container_name: notification-service
    build:
      context: ./notification
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./notification/src:/usr/src/app/src
    command: npm run start:dev

  # 4. Payment Service
  payment_service:
    container_name: payment-service
    build:
      context: ./payment
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    volumes:
      - ./payment/src:/usr/src/app/src
    command: npm run start:dev

  # 5. Subscription Service
  subscription_service:
    container_name: subscription-service
    build:
      context: ./subscription
      dockerfile: Dockerfile
    ports:
      - "3004:3000"
    volumes:
      - ./subscription/src:/usr/src/app/src
    command: npm run start:dev

  # 6.User Service
  user_service:
    container_name: user-service
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - user_service_db
    volumes:
      - ./user/src:/usr/src/app/src

  user_service_db:
    container_name: user-service-db
    image: mysql
    ports:
      - '3307:3307'
    env_file:
      - ./user/.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TCP_PORT=3307




